### ISSUE TITLE
Tag 0.9.23 planned?

### ISSUE THREAD

**Issue by batkins61** [unfs3/unfs3#23]
Assuming master is stable, is there a version bump planned? (e.g. 0.9.23)?

**Comment by CendioOssman** [comment]
#17 should probably be completed first. And possibly #20. It's difficult to build this on current systems otherwise.

**Comment by amjoseph-nixpkgs** [comment]
This issue got closed, but the tag wasn't created... now that #17 has been merged would you mind tagging a release?  This makes it easier for downstream projects to make the update.  In particular, in the case of nixpkgs, unfs3 is currently marked broken (due to none of the tagged releases building with current glibc) and is at risk of being dropped when the next release happens.

**Comment by CendioOssman** [comment]
Sure. I can have a look at putting a new tag. Might be worth calling it 0.10.0 given the large change in base requirements.
