### ISSUE TITLE
getsockopt: Function not implemented

### ISSUE THREAD

**Issue by m8522s** [unfs3/unfs3#27]
I try to run `unfsd` on a VMware ESXi server. When starting `unfsd` on ESXi 7.0.3, I get the error:
```
getsockopt: Function not implemented
```

I unterstand that libc on ESXi does not include getsockopt and setsockopt, which is used by `daemon.c`.
My questions are:
- Is it possible to migrate `unfsd`, so it will run on ESXi?
- Is there an alternative to getsockopt()?
- Will static linking help?

Thanks for your help!

**Comment by CendioOssman** [comment]
> * Is it possible to migrate `unfsd`, so it will run on ESXi?
> 
> * Is there an alternative to getsockopt()?

Maybe, but not something we're aware of. UNFS3 is made for POSIX systems, and it sounds like ESXi unfortunately doesn't qualify for that. :/

> 
>     * Will static linking help?

Very unlikely. It is probably missing from their libc because it is also missing from their kernel. And besides, is there any other libc available for ESXi that could be linked?
